### ISSUE TITLE
Add "data value"/age support for SWEET_BERRY_BUSH

### ISSUE THREAD

**Issue by MarvinKlar** [CoolLord22/OtherDrops#112]
**Is your feature request related to a problem? Please describe.**
I am currently trying to change the drops of consumables like wheat, carrots and berry bushes. The following triggers for the SWEET_BERRY_BUSH seem not to work:
```
defaults:
    worlds: ALL

otherdrops:
    SWEET_BERRY_BUSH@0:
        - trigger: BREAK
          drop: AIR
          command: ["/!$say SWEET_BERRY_BUSH@0"]
    SWEET_BERRY_BUSH@1:
        - trigger: BREAK
          drop: AIR
          command: ["/!$say SWEET_BERRY_BUSH@1"]
    SWEET_BERRY_BUSH@2:
        - trigger: BREAK
          drop: AIR
          command: ["/!$say SWEET_BERRY_BUSH@2"]
        - trigger: RIGHT_CLICK
          replaceblock: SWEET_BERRY_BUSH@1
          drop: AIR
          command: ["/!$say SWEET_BERRY_BUSH@2"]
    SWEET_BERRY_BUSH@3:
        - trigger: BREAK
          drop: AIR
          command: ["/!$say SWEET_BERRY_BUSH@3"]
        - trigger: RIGHT_CLICK
          replaceblock: SWEET_BERRY_BUSH@1
          drop: AIR
          command: ["/!$say SWEET_BERRY_BUSH@3"]
```

I would expect the plugin to print `SWEET_BERRY_BUSH@3` when I break a full grown berry bush, but it always prints `SWEET_BERRY_BUSH@0`

Screenshot:
https://prnt.sc/OwAHDT_2hNaO
