### ISSUE TITLE
Feature Request: Add support for drops only from naturally ocurring or player-placed blocks

### ISSUE THREAD

**Issue by flareglare** [CoolLord22/OtherDrops#92]
**Is your feature request related to a problem? Please describe.**
Idea: Have a custom drop only from a block that was naturally existent in the world such as tree logs. Configuration proceeds as with any other block and drop. 
> I had an idea to make use out of axe with fortune enchantment, but that would be silly if player could just place a bunch of wood and destroy it to get much more wood than he had originally

**Describe the solution you'd like**
Have a block modifier (like `LOG@NARUTAL` or `LOG@PLACED`). Of course it's up to developers, this is just my proposition.

**Comment by CoolLord22** [comment]
Added in support to limit block drops to blocks either occurring naturally in the world or those placed by players! Please note, this will only start tracking all blocks placed **AFTER** installing this version. Meaning, all player-placed blocks before this release will still count as "naturally" occurring blocks. You can use the new condition `placedby` as you would use `spawnedby:` for creatures. Please see below for valid config example! Valid tags for the  `placedby` condition are `PLAYER` and `NATURAL`. Note, only added on 1.13Plus.

```yaml
    DIRT:
        - message: A block placed by a player
          placedby: PLAYER
          
        - message: A block not placed by player
          placedby: -PLAYER
          
        - message: A naturally placed block
          placedby: NATURAL

        - message: A block not naturally placed
          placedby: -NATURAL
```
[OtherDrops1.13Plus-b71.jar.zip](https://github.com/CoolLord22/OtherDrops/files/10800351/OtherDrops1.13Plus-b71.jar.zip)
